# Generated by Django 4.2.6 on 2024-11-26 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_reto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
